# environments:
#   staging: &staging
#     values:
#       - phase: staging
#   production:
#     values:
#       - phase: production
#   default: *staging

repositories:
  - name: stable
    url: https://charts.helm.sh/stable

  # apollo/apollo-service
  # apollo/apollo-portal
  - name: apollo
    url: https://www.apolloconfig.com/charts
  
  # elastic/elasticsearch
  # elastic/logstash
  # elastic/kibana
  - name: elastic
    url: https://helm.elastic.co

  # bitnami/zookeeper
  # bitnami/kafka
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  # # choerodon/sonatype-nexus
  # - name: choerodon
  #   url: https://openchart.choerodon.com.cn/choerodon/c7n

  # oteemocharts/sonatype-nexus
  - name: oteemocharts
    url: https://oteemo.github.io/charts



releases:
  # mysql
  - name: mysql
    namespace: ctexcelhk
    chart: charts/mysql
    version: 8.8.6
    values:
      - values/mysql.yaml

  # nacos
  - name: nacos
    namespace: ctexcelhk
    chart: "charts/nacos"
    version: 0.1.5
    values:
      - "values/nacos.yaml"

  # elasticsearch
  - name: elasticsearch
    namespace: ctexcelhk
    chart: elastic/elasticsearch
    version: 7.5.1
    values:
      - values/elasticsearch.yaml

  # logstash
  - name: logstash
    namespace: ctexcelhk
    chart: elastic/logstash
    version: 7.14.0
    values:
      - values/logstash.yaml

  # skywalking
  - name: skywalking
    namespace: ctexcelhk
    chart: charts/skywalking
    version: 4.1.0
    values:
      - values/skywalking-base.yaml
      - values/skywalking.yaml

  # zookeeper
  - name: zookeeper-test
    namespace: ctexcelhk
    chart: bitnami/zookeeper
    version: 6.5.3
    values:
      - values/zookeeper.yaml

  # kafka
  - name: kafka
    namespace: ctexcelhk
    chart: bitnami/kafka
    version: 12.17.3
    values:
      - values/kafka.yaml

  # sonatype-nexus
  - name: nexus
    namespace: ctexcelhk
    chart: oteemocharts/sonatype-nexus
    version: 5.2.1
    values:
      - values/nexus.yaml

  # apollo-service-pro
  - name: apollo-service-pro
    namespace: ctexcelhk
    chart: apollo/apollo-service
    version: 0.3.0
    values:
      - values/apollo-service-pro.yaml
  
  # apollo-service-test
  - name: apollo-service-test
    namespace: ctexcelhk
    chart: apollo/apollo-service
    version: 0.3.0
    values:
      - values/apollo-service-test.yaml

  # apollo-portal
  - name: apollo-portal
    namespace: ctexcelhk
    chart: apollo/apollo-portal
    version: 0.3.0
    values:
      - values/apollo-portal.yaml
